### ISSUE TITLE
Problem creating services

### ISSUE THREAD

**Issue by david-rojo** [saurabh-hirani/icinga2-api-examples#3]
Thanks for this useful repo! I am trying to execute the examples that you have provided but I have an issue creating the dummy service.

I create succesfully hostgroups and hosts but when I execute the command that creates the api_dummy_service_1 service for api_dummy_host_1 host:
```
curl -u $ICINGA2_API_USER:$ICINGA2_API_PASSWORD  \
     -H 'Accept: application/json' -X PUT \
     -k "https://$ICINGA2_HOST:$ICINGA2_API_PORT/v1/objects/services/api_dummy_host_1!api_dummy_service_1" \
     -d '{ "templates": [ "generic-service" ], "attrs": { "display_name": "api_dummy_service_1", "check_command" : "dns", "vars.dns_lookup": "google-public-dns-a.google.com.", "vars.dns_expected_answer": "8.8.8.8", "host_name": "api_dummy_host_1" } }' | python -m json.tool
```
The following error message appears: `
-bash: !api_dummy_service_1: event not found
`
I have tried to have a look to Icinga logs and search information related to this in internet with no results. Can you help me please?

I am using Icinga 2.4.0. Thanks in advance!

**Comment by david-rojo** [comment]
Issue fixed! After doing more test in detail we have detected that the problem was related to the URL that we use to connect with icinga2 API, the ! character must be escaped.

I have changed ! to %21 and the command works.

**Comment by saurabh-hirani** [comment]
Cool. Thanks for the update!
