### ISSUE TITLE
Service checks shows wrong result

### ISSUE THREAD

**Issue by pkhadka56** [saurabh-hirani/icinga2-api-examples#5]
For example if you check cpu load service then it will check master icinga2 server load instead of client server.

**Comment by saurabh-hirani** [comment]
I don't think I understood this clearly. If you think it is a flaw with the example, then could you point out the specific example, the flaw and the fix? If you think that's how icinga2 behaves then could you reach out to the community on https://dev.icinga.org/issues/  to report it?

**Comment by pkhadka56** [comment]
Thanks for your reply. Have you checked any other service like cpu load? I tried to check other services like disk, load, mailq etc and it showed me status of master server. It should be giving result from client servers isn't it. 

I do not know if this is flaw.

Example to check load service:

```
#!/bin/bash -e

. icinga2_vars

echo "creating load service" 

curl -s -u $ICINGA2_API_USER:$ICINGA2_API_PASSWORD  \
     -H 'Accept: application/json' -X PUT \
     -k "https://$ICINGA2_HOST:$ICINGA2_API_PORT/v1/objects/services/clientserver.com!load" \
     -d '{ 
        "templates": [ "generic-service" ], 
        "attrs": { 
          "display_name": "check load", 
          "check_command" : "load", 
          "host_name": "clientserver.com", 
	  "check_interval": 1,
	  "retry_interval": 1,
	  "command_endpoint": "clientserver.com"
          } 
          }' | python -m json.tool
))
```

This gives me result from master.com instead of clientserver.com. Let me know if you want any further example.

**Comment by saurabh-hirani** [comment]
I haven't playing with icinga2 in over the last 2 years as is the case that my current firm isn't using it and hence I am not that clued in the day to day work. Closing this issue as there hasn't been any traction on it.
