### ISSUE TITLE
Schedule downtime for a Single service check in Icinga2 via API

### ISSUE THREAD

**Issue by ananthaa-advisory** [saurabh-hirani/icinga2-api-examples#6]
Hi Saurabh,

I was looking for a API to schedule downtime for  a single service check. I do have a API for scheduling downtime for all service checks under one Host. Is there a API for creating downtime only for one service under one host. Its been more than a week iam trying to figure out that.

This is what I got:

I am passing two argument in the below API call:

> curl -u 'root:icinga' -s -k  -H 'Accept: application/json' -X POST "https://localhost:5665/v1/actions/schedule-downtime" -d '{ "type": "Host", "filter": "host.name==\"demo01.sample.com\"", "start_time": "'"$NOW"'", "end_time": "'"$END_TIME"'", "author": "testuser",  "comment": "hello", "fixed": true, "duration": 30}' | python -m json.tool | grep "Successfully scheduled downtime"

**Comment by saurabh-hirani** [comment]
Hi,

I haven't playing with icinga2 in over an year as is the case that my current firm isn't using it and hence I am not that clued in the day to day work. Your best bet is to reach out to the @icinga twitter handle. I'm no longer in the zone to look it up from any rough notes and provide an answer. I too, would do the same level of R & D as you would. Having said that - I used to refer mostly to https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#schedule-downtime to get all my queries answered. If there is a gap - it would be good to call it out on twitter. The community members are very friendly and approachable.

**Comment by anthonyloukinas** [comment]
@ananthaa-advisory Did you reach out and receive an answer? We are trying to do the same thing.

**Comment by zerosoul13** [comment]
According to docs, this is in fact possible.

The example shared shows a filter for a Host type but it can also work with
a Service type filter.

**Comment by anthonyloukinas** [comment]
@zerosoul13 They state directly in the docs that you can schedule downtime to Hosts or Services with the type variable, but the question that is being asked is how to schedule downtime for a specific service on a single host. 

The API (based on documentation and examples), don't seemingly let you do that. It only lets you schedule downtime for all services matching a filter (for all hosts with that service), or all services on a specific Host.
